# inherit from the proprietary version
-include vendor/tcl/5059d/BoardConfigVendor.mk

# GPS
TARGET_SPECIFIC_HEADER_PATH := device/tcl/5059d/include

# Platform
TARGET_BOARD_PLATFORM := mt6739
TARGET_NO_BOOTLOADER := true

#FORCE_32_BIT = true

# Architecture
ifeq ($(FORCE_32_BIT),true)
	TARGET_ARCH := arm
	TARGET_ARCH_VARIANT := armv7-a-neon
	TARGET_CPU_ABI := armeabi-v7a
	TARGET_CPU_ABI2 := armeabi
	TARGET_CPU_VARIANT := cortex-a53
else
	TARGET_ARCH := arm64
	TARGET_ARCH_VARIANT := armv8-a
	TARGET_CPU_ABI := arm64-v8a
	TARGET_CPU_ABI2 :=
	TARGET_CPU_VARIANT := cortex-a53

	TARGET_2ND_ARCH := arm
	TARGET_2ND_ARCH_VARIANT := armv7-a-neon
	TARGET_2ND_CPU_ABI := armeabi-v7a
	TARGET_2ND_CPU_ABI2 := armeabi
	TARGET_2ND_CPU_VARIANT := cortex-a53

	TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
	TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
	TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)

	#TARGET_CPU_ABI_LIST := arm64-v8a,armeabi-v7a,armeabi
	#TARGET_CPU_ABI_LIST_32_BIT := armeabi-v7a,armeabi
	#TARGET_CPU_ABI_LIST_64_BIT := arm64-v8a
endif

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := mt6739

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1 androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048

# make_ext4fs requires numbers in dec format
BOARD_BOOTIMAGE_PARTITION_SIZE := 25165824 
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 25165824 
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2835349504
BOARD_USERDATAIMAGE_PARTITION_SIZE := 11319360512
BOARD_CACHEIMAGE_PARTITION_SIZE := 452984832
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/tcl/5059d/kernel
#BOARD_CUSTOM_BOOTIMG_MK := device/tcl/5059d/bootimg.mk
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x05000000 --tags_offset 0x04000000 
BOARD_CUSTOM_BOOTIMG := true

TARGET_KMODULES := true

# Assert
TARGET_OTA_ASSERT_DEVICE := 5059d,5059d_tcl,tcl_5059d,tcl_5059d,"Alcatel 1X",alcatel_5059d,alcatel_1x

#COMMON_GLOBAL_CFLAGS += -DDISABLE_HW_ID_MATCH_CHECK
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true

# Disable memcpy opt (for audio libraries)
TARGET_CPU_MEMCPY_OPT_DISABLE := true

# EGL
BOARD_EGL_CFG := device/tcl/5059d/configs/egl.cfg
USE_OPENGL_RENDERER := true
BOARD_EGL_WORKAROUND_BUG_10194508 := true
TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true

# MTK Hardware
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true
#COMMON_GLOBAL_CFLAGS += -DMTK_HARDWARE -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL
#COMMON_GLOBAL_CPPFLAGS += -DMTK_HARDWARE

# Offline charging
BOARD_CHARGING_MODE_BOOTING_LPM := /sys/class/BOOT/BOOT/boot/boot_mode

# RIL
BOARD_RIL_CLASS := ../../../device/tcl/5059d/ril/

BOARD_CONNECTIVITY_VENDOR := MediaTek
BOARD_CONNECTIVITY_MODULE := conn_soc

# WIFI
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_FW_PATH_PARAM:="/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA:=STA
WIFI_DRIVER_FW_PATH_AP:=AP
WIFI_DRIVER_FW_PATH_P2P:=P2P

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/tcl/5059d/bluetooth

# Sensors
TARGET_NO_SENSOR_PERMISSION_CHECK := true

# CWM
TARGET_RECOVERY_FSTAB := device/tcl/5059d/rootdir/root/recovery.fstab
TARGET_PREBUILT_RECOVERY_KERNEL := device/tcl/5059d/kernel
BOARD_HAS_NO_SELECT_BUTTON := true

# TWRP stuff
TW_THEME := portrait_hdpi
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_NO_REBOOT_BOOTLOADER := true
TW_BRIGHTNESS_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/musb-hdrc.0.auto/gadget/lun%d/file
TW_MAX_BRIGHTNESS := 255
TW_EXCLUDE_SUPERSU := true
TW_INCLUDE_FB2PNG := true
TW_NO_CPU_TEMP := true
TW_REBOOT_BOOTLOADER := true
TW_REBOOT_RECOVERY := true
TW_HAS_DOWNLOAD_MODE := true
TW_EXCLUDE_SUPERSU := true
TW_USE_TOOLBOX := true

BOARD_SEPOLICY_DIRS := \
       device/tcl/5059d/sepolicy

# Use old sepolicy version
POLICYVERS := 29

BLOCK_BASED_OTA := false
TARGET_LDPRELOAD += libxlog.so:libmtk_symbols.so

#BOARD_USES_LEGACY_MTK_AV_BLOB := true
#TARGET_HAS_LEGACY_CAMERA_HAL1 := true
